apiVersion: apps/v1
kind: Deployment
metadata:
  name: testk8s-deployment
  labels:
    app: testk8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testk8s
  template:
    metadata:
      labels:
        app: testk8s
    spec:
      containers:
      - name: testk8s-deployment
        image: ghcr.io/timmeiwald/testk8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # testk8s listens on 80
---
kind: Service
apiVersion: v1
metadata:
  name: testk8s-deployment
spec:
  type: ClusterIP
  selector:
    app: testk8s
  ports:
  - protocol: TCP
    port: 82 # Service listens on 82 where ingress sends traffic
    targetPort: 80 # Service then sends to port 80 on testk8s