apiVersion: apps/v1
kind: Deployment
metadata:
  name: testk8s-deployment
  labels:
    app: testk8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testk8s
  template:
    metadata:
      labels:
        app: testk8s
    spec:
      containers:
        - name: testk8s-deployment
          image: ghcr.io/timmeiwald/testk8s
          imagePullPolicy: Always
          ports:
          - containerPort: 80 # testk8s listens on 80
          env:
          - name: NODE_ID
            value: {{ spec.nodeName }}
          - name: POD_ID
            value: {{ metadata.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: testk8s-service
  labels:
    app: testk8s
spec:
  selector:
    app: testk8s
  ports:
    - port: 80
