on: push
jobs:
    example-job:
     runs-on: ubuntu-latest
     steps:
       # Checkout the code
       - name: Checkout Repo
         uses: actions/checkout@v2
       # Login to docker
       # This can be used for both Docker Hub and
       # GitHub container registry.
       - 
        name: Login to GitHub Container Registry       
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}


       # Build the docker image and push it.
       - name: Build image
         uses: docker/build-push-action@v3
         with:
           context: .
           push: true
           # Remove the `gchr.io/` if you're pushing to
           # Docker Hub
           tags: ghcr.io/owner/testk8s:latest
 