on: push
jobs:
    example-job:
     runs-on: ubuntu-latest
     steps:
       # Checkout the code
       - name: Checkout Repo
         uses: actions/checkout@v2
       # Login to docker
       # This can be used for both Docker Hub and
       # GitHub container registry.
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v2
         with:
           # Remove the following line if you want to
           # login to docker hub.
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           # secrets are GitHub actions that can be added
           # from settings of the repo.
           password: ${{ secrets.CR_PAT }}
       # Build the docker image and push it.
       - name: Build image
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           # Remove the `gchr.io/` if you're pushing to
           # Docker Hub
           tags: ghcr.io/owner/packageName:latest
 